declare module TcHmi {
    module Controls {
        module ResponsiveNavigation {
            class TcHmiNavigationContent extends TcHmi.Controls.System.TcHmiControl {
                constructor(element: JQuery, pcElement: JQuery, attrs: TcHmi.Controls.ControlAttributeList);
                protected __curRowElement: JQuery | null | undefined;
                protected __lastExpandedElement: HTMLElement | null | undefined;
                protected __lastExpandedSubElement: HTMLElement | null | undefined;
                protected __slideUpTime: number | null | undefined;
                protected __slideDownTime: number | null | undefined;
                protected __menuSourceData: any;
                protected __masterID: string | null | undefined;
                protected __masterControl: any;
                protected __mouseOverShow: string | null | undefined;
                protected __mobileView: boolean | null | undefined;
                protected __paddingLeftRight: number | null | undefined;
                protected __paddingLeftRightUnit: string | null | undefined;
                protected __columnElementMarginTop: number | null | undefined;
                protected __columnElementMarginTopUnit: string | null | undefined;
                protected __mobileElementMarginTop: number | null | undefined;
                protected __mobileElementMarginTopUnit: string | null | undefined;
                protected __showIconsMobile: boolean | null | undefined;
                protected __closeText: string | null | undefined;
                protected __showMenuEvents: string | null | undefined;
                protected __autoCollapseElements: boolean | null | undefined;
                protected __subtitleFontSize: number | null | undefined;
                protected __subtitleFontSizeUnit: string | null | undefined;
                protected __columnTitleFontSize: number | null | undefined;
                protected __columnTitleFontSizeUnit: string | null | undefined;
                protected __columnElementFontSize: number | null | undefined;
                protected __columnElementFontSizeUnit: string | null | undefined;
                protected __closeFontSize: number | null | undefined;
                protected __closeFontSizeUnit: string | null | undefined;
                protected __fontColor: SolidColor | null;
                protected __menuBackgroundColor: Color | null;
                protected __closeImage: string | null | undefined;
                protected __subMenuImage: string | null | undefined;
                protected __elementTemplateRoot: JQuery | null | undefined;
                protected __elementNavigationContent: JQuery | null | undefined;
                protected __elementNavigationLine: JQuery | null | undefined;
                __previnit(): void;
                __init(): void;
                __attach(): void;
                __detach(): void;
                destroy(): void;
                /************************************** Setter getter processor **************************************/
                setPaddingLeftRight(valueNew: number | null): void;
                getPaddingLeftRight(): number | null | undefined;
                protected __processPaddingLeftRight(): void;
                setPaddingLeftRightUnit(valueNew: string | null): void;
                getPaddingLeftRightUnit(): string | null | undefined;
                protected __processPaddingLeftRightUnit(): void;
                setColumnElementMarginTop(valueNew: number | null): void;
                getColumnElementMarginTop(): number | null | undefined;
                protected __processColumnElementMarginTop(): void;
                setColumnElementMarginTopUnit(valueNew: string | null): void;
                getColumnElementMarginTopUnit(): string | null | undefined;
                protected __processColumnElementMarginTopUnit(): void;
                setMobileElementMarginTop(valueNew: number | null): void;
                getMobileElementMarginTop(): number | null | undefined;
                protected __processMobileElementMarginTop(): void;
                setMobileElementMarginTopUnit(valueNew: string | null): void;
                getMobileElementMarginTopUnit(): string | null | undefined;
                protected __processMobileElementMarginTopUnit(): void;
                setSubtitleFontSize(valueNew: number | null): void;
                getSubtitleFontSize(): number | null | undefined;
                protected __processSubtitleFontSize(): void;
                setSubtitleFontSizeUnit(valueNew: string | null): void;
                getSubtitleFontSizeUnit(): string | null | undefined;
                protected __processSubtitleFontSizeUnit(): void;
                setColumnTitleFontSize(valueNew: number | null): void;
                getColumnTitleFontSize(): number | null | undefined;
                protected __processColumnTitleFontSize(): void;
                setColumnTitleFontSizeUnit(valueNew: string | null): void;
                getColumnTitleFontSizeUnit(): string | null | undefined;
                protected __processColumnTitleFontSizeUnit(): void;
                setColumnElementFontSize(valueNew: number | null): void;
                getColumnElementFontSize(): number | null | undefined;
                protected __processColumnElementFontSize(): void;
                setColumnElementFontSizeUnit(valueNew: string | null): void;
                getColumnElementFontSizeUnit(): string | null | undefined;
                protected __processColumnElementFontSizeUnit(): void;
                setCloseFontSize(valueNew: number | null): void;
                getCloseFontSize(): number | null | undefined;
                protected __processCloseFontSize(): void;
                setCloseFontSizeUnit(valueNew: string | null): void;
                getCloseFontSizeUnit(): string | null | undefined;
                protected __processCloseFontSizeUnit(): void;
                setShowIconsMobile(valueNew: boolean | null): void;
                getShowIconsMobile(): boolean | null | undefined;
                protected __processShowIconsMobile(): void;
                setAutoCollapseElements(valueNew: boolean | null): void;
                getAutoCollapseElements(): boolean | null | undefined;
                protected __processAutoCollapseElements(): void;
                setFontColor(valueNew: SolidColor | null): void;
                getFontColor(): SolidColor | null;
                protected __processFontColor(): void;
                setMenuBackgroundColor(valueNew: Color | null): void;
                getMenuBackgroundColor(): SolidColor | LinearGradientColor | null;
                protected __processMenuBackgroundColor(): void;
                setCloseText(valueNew: string | null): void;
                getCloseText(): string | null | undefined;
                protected __processCloseText(): void;
                protected __initializeAccessConfig(): void;
                getAccessConfig(): AccessControl[];
                getDescriptionAccessByName(): {
                    defaultValueInternal: boolean;
                };
                protected __getSubRights(dataObject: any, accessList: any): any;
                setCloseImage(valueNew: string | null): void;
                getCloseImage(): string | null | undefined;
                protected __processCloseImage(): void;
                setSubMenuImage(valueNew: string | null): void;
                getSubMenuImage(): string | null | undefined;
                protected __processSubMenuImage(): void;
                /****************** interfaces ********************/
                protected __closeMenu(): void;
                protected __callOnPageCalled(eventName: string | null | undefined, dataId: string | null | undefined, page: string | null | undefined): void;
                protected __setLastHeadId(id: string | undefined): void;
                loadContentView(curHeadIndex: string | undefined, mobileView: any, enableMobileSwitch: any, alignment: any): void;
                setMenuSourceData(valueNew: any | null): void;
                setMasterID(valueNew: string | null): void;
                setShowMenuEvents(mouseOverShow: any, menuEvents: any): void;
                protected __showNavContent(alignment: string): void;
                hideNavContent(): void;
                /****************** functions ********************/
                protected __getColorOfColorObject(colorObject: SolidColor | null | undefined): string | null;
                protected __clearContent(): void;
                protected __hasChildren(elementList: any, index: number | string | undefined): boolean;
                protected __isNotEmpty(element: any): boolean;
                protected __round2Decimals(value: number): number;
                protected __loadContent(curHeadIndex: any, enableMobileSwitch: any): void;
                protected __onOutsideElementsCloseHandler(): (this: HTMLElement, e: any) => void;
                protected __getCloseContentElement(): JQuery<HTMLElement>;
                protected __createDesktopContent(curHeadIndex: any): JQuery<HTMLElement>;
                protected __createSubElements(elementContainer: any): JQuery<HTMLElement>;
                protected __onSubElementFunctionHandler(): (this: HTMLElement, e: any) => void;
                protected __closeAllButNotMe(element: JQuery, $this: any): void;
                protected __openSubElement(element: HTMLElement, slideDownTime: number, mobileView: boolean): void;
                protected __closeSubElement(element: HTMLElement, slideUpTime: number, mobileView: boolean): void;
                protected __openElement(element: HTMLElement, slideDownTime: number): void;
                protected __closeElement(element: HTMLElement, slideUpTime: number): void;
                protected __createMobileContent(): JQuery<HTMLElement>;
                protected __createFirstHierarchyMobile(elementContainer: any): JQuery<HTMLElement>;
            }
        }
    }
}
